# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configs are located in `ygo-fabrica/config.toml`,
#  check that file to see possible settings.

[expansion.lyris]
default = true
recipe = []

[picset.lyris]
mode = 'proxy'
size = '421x611'
ext = 'png'
year = '2020'
author = 'YGOCC/Studio Dice/SHUEISHA, TV TOKYO, KONAMI'
field = true
default = true
holo = false
