--Clear Pixie
function c101010149.initial_effect(c)
	--hand
	local ae1=Effect.CreateEffect(c)
	ae1:SetCategory(CATEGORY_TODECK)
	ae1:SetType(EFFECT_TYPE_IGNITION)
	ae1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	ae1:SetRange(LOCATION_MZONE)
	ae1:SetCountLimit(1)
	ae1:SetCondition(c101010149.con)
	ae1:SetTarget(c101010149.dctg)
	ae1:SetOperation(c101010149.dcop)
	c:RegisterEffect(ae1)
	--immune
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD)
	e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
	e1:SetRange(LOCATION_MZONE)
	e1:SetTargetRange(1,0)
	e1:SetCode(97811903)
	e1:SetCondition(c101010149.tpcon)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetTargetRange(0,1)
	e2:SetCondition(c101010149.ntpcon)
	c:RegisterEffect(e2)
	--cannot be material
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_SINGLE)
	e3:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCode(EFFECT_UNRELEASABLE_SUM)
	e3:SetValue(1)
	e3:SetCondition(c101010149.ntpcon)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EFFECT_UNRELEASABLE_NONSUM)
	c:RegisterEffect(e4)
	local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_SINGLE)
	e5:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	e5:SetCode(EFFECT_CANNOT_BE_FUSION_MATERIAL)
	e5:SetValue(1)
	e5:SetCondition(c101010149.ntpcon)
	c:RegisterEffect(e5)
	local e6=e5:Clone()
	e6:SetCode(EFFECT_CANNOT_BE_SYNCHRO_MATERIAL)
	c:RegisterEffect(e6)
	local e7=e5:Clone()
	e7:SetCode(EFFECT_CANNOT_BE_XYZ_MATERIAL)
	c:RegisterEffect(e7)
end
function c101010149.tpcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsLocation(LOCATION_MZONE) and c:IsControler(c:GetOwner())
end
function c101010149.ntpcon(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	return c:IsLocation(LOCATION_MZONE) and c:IsControler(1-c:GetOwner())
end
function c101010149.filter(c)
	return c:IsFaceup() and c:IsAttribute(ATTRIBUTE_LIGHT)
end
function c101010149.con(e,tp,eg,ep,ev,re,r,rp)
	return c101010149.tpcon(e,tp,eg,ep,ev,re,r,rp) and Duel.IsExistingMatchingCard(c101010149.filter,tp,0,LOCATION_MZONE,1,nil)
end
function c101010149.dctg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.GetFieldGroupCount(tp,0,LOCATION_HAND)>0 end
	Duel.SetTargetPlayer(tp)
	Duel.SetOperationInfo(0,CATEGORY_HANDES,nil,0,1-tp,1)
end
function c101010149.dcop(e,tp,eg,ep,ev,re,r,rp)
	local p=Duel.GetChainInfo(0,CHAININFO_TARGET_PLAYER)
	if Duel.GetFieldGroupCount(p,0,LOCATION_HAND)==0 or not Duel.IsExistingMatchingCard(c101010149.filter,p,0,LOCATION_MZONE,1,nil) then return end
	local g=Duel.GetFieldGroup(p,0,LOCATION_HAND)
	Duel.Hint(HINT_SELECTMSG,p,HINTMSG_DISCARD)
	local sg=g:Select(p,1,1,nil)
	Duel.SendtoGrave(sg,REASON_EFFECT+REASON_DISCARD)
end
